/**
 * Tool: post_api_v1_chat_pinMessage
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_chat_pinMessage",
  description: "chat.pinMessage(messageId:o)", //  The TOON Context Saver
  inputSchema: z.object({
    messageId: z.string(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/chat.pinMessage"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.messageId !== undefined) {
       const value = encodeURIComponent(String(args.messageId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "messageId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("messageId", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
