/**
 * Tool: post_api_v1_roles_addUserToRole
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_roles_addUserToRole",
  description: "roles.addUserToRole([roleId:o], u:o, [rid:o])", //  The TOON Context Saver
  inputSchema: z.object({
    roleId: z.string().optional(),
    username: z.string(),
    roomId: z.string().optional(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/roles.addUserToRole"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.roleId !== undefined) {
       const value = encodeURIComponent(String(args.roleId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "roleId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("roleId", value);
    }
    if (args.username !== undefined) {
       const value = encodeURIComponent(String(args.username));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "username" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("username", value);
    }
    if (args.roomId !== undefined) {
       const value = encodeURIComponent(String(args.roomId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "roomId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("roomId", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
