#!/usr/bin/env node
/**
 * rc-content-moderation-mcp — MCP Server
 * Auto-generated by Minimal-MCP-Architect
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { initAuth } from "./rc-client.js";

// Import generated tools
import { tool as get_api_v1_chat_getMessage } from "./tools/get_api_v1_chat_getMessage.js";
import { tool as post_api_v1_chat_delete } from "./tools/post_api_v1_chat_delete.js";
import { tool as post_api_v1_users_setActiveStatus } from "./tools/post_api_v1_users_setActiveStatus.js";
import { tool as post_api_v1_chat_postMessage } from "./tools/post_api_v1_chat_postMessage.js";
import { tool as moderate_message } from "./tools/moderate_message.js";

const server = new McpServer({ 
  name: "rc-content-moderation-mcp", 
  version: "1.0.0" 
});

// Register tools
server.registerTool(
  moderate_message.name,
  {
    description: moderate_message.description,
    inputSchema: moderate_message.inputSchema
  },
  moderate_message.handler
);
server.registerTool(
  get_api_v1_chat_getMessage.name,
  {
    description: get_api_v1_chat_getMessage.description,
    inputSchema: get_api_v1_chat_getMessage.inputSchema
  },
  get_api_v1_chat_getMessage.handler
);
server.registerTool(
  post_api_v1_chat_delete.name,
  {
    description: post_api_v1_chat_delete.description,
    inputSchema: post_api_v1_chat_delete.inputSchema
  },
  post_api_v1_chat_delete.handler
);
server.registerTool(
  post_api_v1_users_setActiveStatus.name,
  {
    description: post_api_v1_users_setActiveStatus.description,
    inputSchema: post_api_v1_users_setActiveStatus.inputSchema
  },
  post_api_v1_users_setActiveStatus.handler
);
server.registerTool(
  post_api_v1_chat_postMessage.name,
  {
    description: post_api_v1_chat_postMessage.description,
    inputSchema: post_api_v1_chat_postMessage.inputSchema
  },
  post_api_v1_chat_postMessage.handler
);

async function main() {
  console.error("Initializing Rocket.Chat Auth...");
  await initAuth();
  
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("rc-content-moderation-mcp running on stdio — 5 tools active.");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
