#!/usr/bin/env node
/**
 * rc-stats-server — MCP Server
 * Auto-generated by Minimal-MCP-Architect
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { initAuth } from "./rc-client.js";

// Import generated tools
import { tool as get_api_v1_statistics } from "./tools/get_api_v1_statistics.js";

const server = new McpServer({ 
  name: "rc-stats-server", 
  version: "1.0.0" 
});

// Register tools
server.registerTool(
  get_api_v1_statistics.name,
  {
    description: get_api_v1_statistics.description,
    inputSchema: get_api_v1_statistics.inputSchema
  },
  get_api_v1_statistics.handler
);

async function main() {
  console.error("Initializing Rocket.Chat Auth...");
  await initAuth();
  
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("rc-stats-server running on stdio — 1 tools active.");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
