#!/usr/bin/env node
/**
 * rc-admin-dashboard-mcp — MCP Server
 * Auto-generated by Minimal-MCP-Architect
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { initAuth } from "./rc-client.js";

// Import generated tools
import { tool as get_api_v1_statistics } from "./tools/get_api_v1_statistics.js";
import { tool as get_api_v1_engagement_dashboard_users_active_users } from "./tools/get_api_v1_engagement_dashboard_users_active_users.js";
import { tool as get_api_v1_users_list } from "./tools/get_api_v1_users_list.js";
import { tool as post_api_v1_users_create } from "./tools/post_api_v1_users_create.js";
import { tool as post_api_v1_users_update } from "./tools/post_api_v1_users_update.js";
import { tool as post_api_v1_users_delete } from "./tools/post_api_v1_users_delete.js";
import { tool as get_api_v1_settings } from "./tools/get_api_v1_settings.js";
import { tool as post_api_v1_settings_id } from "./tools/post_api_v1_settings_id.js";
import { tool as get_api_v1_moderation_reports } from "./tools/get_api_v1_moderation_reports.js";
import { tool as post_api_v1_moderation_dismissReports } from "./tools/post_api_v1_moderation_dismissReports.js";
import { tool as get_api_apps_installed } from "./tools/get_api_apps_installed.js";
import { tool as delete_api_apps_appId } from "./tools/delete_api_apps_appId.js";
import { tool as get_api_v1_sessions_list_all } from "./tools/get_api_v1_sessions_list_all.js";
import { tool as post_api_v1_sessions_logout } from "./tools/post_api_v1_sessions_logout.js";

const server = new McpServer({ 
  name: "rc-admin-dashboard-mcp", 
  version: "1.0.0" 
});

// Register tools
server.registerTool(
  get_api_v1_statistics.name,
  {
    description: get_api_v1_statistics.description,
    inputSchema: get_api_v1_statistics.inputSchema
  },
  get_api_v1_statistics.handler
);
server.registerTool(
  get_api_v1_engagement_dashboard_users_active_users.name,
  {
    description: get_api_v1_engagement_dashboard_users_active_users.description,
    inputSchema: get_api_v1_engagement_dashboard_users_active_users.inputSchema
  },
  get_api_v1_engagement_dashboard_users_active_users.handler
);
server.registerTool(
  get_api_v1_users_list.name,
  {
    description: get_api_v1_users_list.description,
    inputSchema: get_api_v1_users_list.inputSchema
  },
  get_api_v1_users_list.handler
);
server.registerTool(
  post_api_v1_users_create.name,
  {
    description: post_api_v1_users_create.description,
    inputSchema: post_api_v1_users_create.inputSchema
  },
  post_api_v1_users_create.handler
);
server.registerTool(
  post_api_v1_users_update.name,
  {
    description: post_api_v1_users_update.description,
    inputSchema: post_api_v1_users_update.inputSchema
  },
  post_api_v1_users_update.handler
);
server.registerTool(
  post_api_v1_users_delete.name,
  {
    description: post_api_v1_users_delete.description,
    inputSchema: post_api_v1_users_delete.inputSchema
  },
  post_api_v1_users_delete.handler
);
server.registerTool(
  get_api_v1_settings.name,
  {
    description: get_api_v1_settings.description,
    inputSchema: get_api_v1_settings.inputSchema
  },
  get_api_v1_settings.handler
);
server.registerTool(
  post_api_v1_settings_id.name,
  {
    description: post_api_v1_settings_id.description,
    inputSchema: post_api_v1_settings_id.inputSchema
  },
  post_api_v1_settings_id.handler
);
server.registerTool(
  get_api_v1_moderation_reports.name,
  {
    description: get_api_v1_moderation_reports.description,
    inputSchema: get_api_v1_moderation_reports.inputSchema
  },
  get_api_v1_moderation_reports.handler
);
server.registerTool(
  post_api_v1_moderation_dismissReports.name,
  {
    description: post_api_v1_moderation_dismissReports.description,
    inputSchema: post_api_v1_moderation_dismissReports.inputSchema
  },
  post_api_v1_moderation_dismissReports.handler
);
server.registerTool(
  get_api_apps_installed.name,
  {
    description: get_api_apps_installed.description,
    inputSchema: get_api_apps_installed.inputSchema
  },
  get_api_apps_installed.handler
);
server.registerTool(
  delete_api_apps_appId.name,
  {
    description: delete_api_apps_appId.description,
    inputSchema: delete_api_apps_appId.inputSchema
  },
  delete_api_apps_appId.handler
);
server.registerTool(
  get_api_v1_sessions_list_all.name,
  {
    description: get_api_v1_sessions_list_all.description,
    inputSchema: get_api_v1_sessions_list_all.inputSchema
  },
  get_api_v1_sessions_list_all.handler
);
server.registerTool(
  post_api_v1_sessions_logout.name,
  {
    description: post_api_v1_sessions_logout.description,
    inputSchema: post_api_v1_sessions_logout.inputSchema
  },
  post_api_v1_sessions_logout.handler
);

async function main() {
  console.error("Initializing Rocket.Chat Auth...");
  await initAuth();
  
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("rc-admin-dashboard-mcp running on stdio — 14 tools active.");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
