/**
 * Tool: post_api_v1_livechat_message
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_livechat_message",
  description: "livechat/message(token:o, rid:o, msg:o, [_id:o], [agent:o])", //  The TOON Context Saver
  inputSchema: z.object({
    token: z.string(),
    rid: z.string(),
    msg: z.string(),
    _id: z.string().optional(),
    agent: z.string().optional(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/livechat/message"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.token !== undefined) {
       const value = encodeURIComponent(String(args.token));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "token" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("token", value);
    }
    if (args.rid !== undefined) {
       const value = encodeURIComponent(String(args.rid));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "rid" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("rid", value);
    }
    if (args.msg !== undefined) {
       const value = encodeURIComponent(String(args.msg));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "msg" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("msg", value);
    }
    if (args._id !== undefined) {
       const value = encodeURIComponent(String(args._id));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "_id" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("_id", value);
    }
    if (args.agent !== undefined) {
       const value = encodeURIComponent(String(args.agent));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "agent" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("agent", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
