/**
 * Tool: post_api_v1_livechat_room_forward
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_livechat_room_forward",
  description: "livechat/room.forward(rid:o, [uid:o], [departmentId:o])", //  The TOON Context Saver
  inputSchema: z.object({
    roomId: z.string(),
    userId: z.string().optional(),
    departmentId: z.string().optional(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/livechat/room.forward"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.roomId !== undefined) {
       const value = encodeURIComponent(String(args.roomId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "roomId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("roomId", value);
    }
    if (args.userId !== undefined) {
       const value = encodeURIComponent(String(args.userId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "userId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("userId", value);
    }
    if (args.departmentId !== undefined) {
       const value = encodeURIComponent(String(args.departmentId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "departmentId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("departmentId", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
