/**
 * Tool: post_api_v1_livechat_inquiries_take
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_livechat_inquiries_take",
  description: "livechat/inquiries.take(inquiryId:o, [uid:o])", //  The TOON Context Saver
  inputSchema: z.object({
    inquiryId: z.string(),
    userId: z.string().optional(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/livechat/inquiries.take"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.inquiryId !== undefined) {
       const value = encodeURIComponent(String(args.inquiryId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "inquiryId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("inquiryId", value);
    }
    if (args.userId !== undefined) {
       const value = encodeURIComponent(String(args.userId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "userId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("userId", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
