#!/usr/bin/env node
/**
 * rc-user-offboarding-mcp — MCP Server
 * Auto-generated by Minimal-MCP-Architect
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { initAuth } from "./rc-client.js";

// Import generated tools
import { tool as post_api_v1_users_setActiveStatus } from "./tools/post_api_v1_users_setActiveStatus.js";
import { tool as post_api_v1_users_logoutOtherClients } from "./tools/post_api_v1_users_logoutOtherClients.js";
import { tool as get_api_v1_users_info } from "./tools/get_api_v1_users_info.js";
import { tool as post_api_v1_channels_kick } from "./tools/post_api_v1_channels_kick.js";
import { tool as post_api_v1_groups_kick } from "./tools/post_api_v1_groups_kick.js";
import { tool as post_api_v1_chat_postMessage } from "./tools/post_api_v1_chat_postMessage.js";
import { tool as offboard_user } from "./tools/offboard_user.js";

const server = new McpServer({ 
  name: "rc-user-offboarding-mcp", 
  version: "1.0.0" 
});

// Register tools
server.registerTool(
  offboard_user.name,
  {
    description: offboard_user.description,
    inputSchema: offboard_user.inputSchema
  },
  offboard_user.handler
);
server.registerTool(
  post_api_v1_users_setActiveStatus.name,
  {
    description: post_api_v1_users_setActiveStatus.description,
    inputSchema: post_api_v1_users_setActiveStatus.inputSchema
  },
  post_api_v1_users_setActiveStatus.handler
);
server.registerTool(
  post_api_v1_users_logoutOtherClients.name,
  {
    description: post_api_v1_users_logoutOtherClients.description,
    inputSchema: post_api_v1_users_logoutOtherClients.inputSchema
  },
  post_api_v1_users_logoutOtherClients.handler
);
server.registerTool(
  get_api_v1_users_info.name,
  {
    description: get_api_v1_users_info.description,
    inputSchema: get_api_v1_users_info.inputSchema
  },
  get_api_v1_users_info.handler
);
server.registerTool(
  post_api_v1_channels_kick.name,
  {
    description: post_api_v1_channels_kick.description,
    inputSchema: post_api_v1_channels_kick.inputSchema
  },
  post_api_v1_channels_kick.handler
);
server.registerTool(
  post_api_v1_groups_kick.name,
  {
    description: post_api_v1_groups_kick.description,
    inputSchema: post_api_v1_groups_kick.inputSchema
  },
  post_api_v1_groups_kick.handler
);
server.registerTool(
  post_api_v1_chat_postMessage.name,
  {
    description: post_api_v1_chat_postMessage.description,
    inputSchema: post_api_v1_chat_postMessage.inputSchema
  },
  post_api_v1_chat_postMessage.handler
);

async function main() {
  console.error("Initializing Rocket.Chat Auth...");
  await initAuth();
  
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("rc-user-offboarding-mcp running on stdio — 6 tools active.");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
