/**
 * Tool: test_tool
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "test_tool",
  description: "test.tool()", //  The TOON Context Saver
  inputSchema: z.object({
    userId: z.string(),
    count: z.number().optional(),
    tags: z.array(z.any()).optional(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/test"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.userId !== undefined) {
       const value = encodeURIComponent(String(args.userId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "userId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("userId", value);
    }
    if (args.count !== undefined) {
       const value = encodeURIComponent(String(args.count));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "count" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("count", value);
    }
    if (args.tags !== undefined) {
       const value = encodeURIComponent(String(args.tags));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "tags" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("tags", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
