#!/usr/bin/env node
/**
 * rc-project-workspace-mcp — MCP Server
 * Auto-generated by Minimal-MCP-Architect
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { initAuth } from "./rc-client.js";

// Import generated tools
import { tool as post_api_v1_groups_create } from "./tools/post_api_v1_groups_create.js";
import { tool as post_api_v1_groups_invite } from "./tools/post_api_v1_groups_invite.js";
import { tool as post_api_v1_integrations_create } from "./tools/post_api_v1_integrations_create.js";
import { tool as post_api_v1_chat_postMessage } from "./tools/post_api_v1_chat_postMessage.js";
import { tool as initialize_project_workspace } from "./tools/initialize_project_workspace.js";

const server = new McpServer({ 
  name: "rc-project-workspace-mcp", 
  version: "1.0.0" 
});

// Register tools
server.registerTool(
  initialize_project_workspace.name,
  {
    description: initialize_project_workspace.description,
    inputSchema: initialize_project_workspace.inputSchema
  },
  initialize_project_workspace.handler
);
server.registerTool(
  post_api_v1_groups_create.name,
  {
    description: post_api_v1_groups_create.description,
    inputSchema: post_api_v1_groups_create.inputSchema
  },
  post_api_v1_groups_create.handler
);
server.registerTool(
  post_api_v1_groups_invite.name,
  {
    description: post_api_v1_groups_invite.description,
    inputSchema: post_api_v1_groups_invite.inputSchema
  },
  post_api_v1_groups_invite.handler
);
server.registerTool(
  post_api_v1_integrations_create.name,
  {
    description: post_api_v1_integrations_create.description,
    inputSchema: post_api_v1_integrations_create.inputSchema
  },
  post_api_v1_integrations_create.handler
);
server.registerTool(
  post_api_v1_chat_postMessage.name,
  {
    description: post_api_v1_chat_postMessage.description,
    inputSchema: post_api_v1_chat_postMessage.inputSchema
  },
  post_api_v1_chat_postMessage.handler
);

async function main() {
  console.error("Initializing Rocket.Chat Auth...");
  await initAuth();
  
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("rc-project-workspace-mcp running on stdio — 4 tools active.");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
