/**
 * Tool: get_api_v1_channels_history
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "get_api_v1_channels_history",
  description: "channels.history()", //  The TOON Context Saver
  inputSchema: z.object({
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/channels.history"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables

    return await rcClient.request("GET", resolvedPath, { body: args });
  }
};
