#!/usr/bin/env node
/**
 * rc-omnichannel-router-mcp — MCP Server
 * Auto-generated by Minimal-MCP-Architect
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { initAuth } from "./rc-client.js";

// Import generated tools
import { tool as get_api_v1_livechat_department } from "./tools/get_api_v1_livechat_department.js";
import { tool as post_api_v1_livechat_room_forward } from "./tools/post_api_v1_livechat_room_forward.js";
import { tool as post_api_v1_livechat_inquiries_take } from "./tools/post_api_v1_livechat_inquiries_take.js";
import { tool as get_api_v1_canned_responses } from "./tools/get_api_v1_canned_responses.js";
import { tool as post_api_v1_livechat_message } from "./tools/post_api_v1_livechat_message.js";

const server = new McpServer({ 
  name: "rc-omnichannel-router-mcp", 
  version: "1.0.0" 
});

// Register tools
server.registerTool(
  get_api_v1_livechat_department.name,
  {
    description: get_api_v1_livechat_department.description,
    inputSchema: get_api_v1_livechat_department.inputSchema
  },
  get_api_v1_livechat_department.handler
);
server.registerTool(
  post_api_v1_livechat_room_forward.name,
  {
    description: post_api_v1_livechat_room_forward.description,
    inputSchema: post_api_v1_livechat_room_forward.inputSchema
  },
  post_api_v1_livechat_room_forward.handler
);
server.registerTool(
  post_api_v1_livechat_inquiries_take.name,
  {
    description: post_api_v1_livechat_inquiries_take.description,
    inputSchema: post_api_v1_livechat_inquiries_take.inputSchema
  },
  post_api_v1_livechat_inquiries_take.handler
);
server.registerTool(
  get_api_v1_canned_responses.name,
  {
    description: get_api_v1_canned_responses.description,
    inputSchema: get_api_v1_canned_responses.inputSchema
  },
  get_api_v1_canned_responses.handler
);
server.registerTool(
  post_api_v1_livechat_message.name,
  {
    description: post_api_v1_livechat_message.description,
    inputSchema: post_api_v1_livechat_message.inputSchema
  },
  post_api_v1_livechat_message.handler
);

async function main() {
  console.error("Initializing Rocket.Chat Auth...");
  await initAuth();
  
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("rc-omnichannel-router-mcp running on stdio — 5 tools active.");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
