#!/usr/bin/env node
/**
 * rc-vendor-provisioning-mcp — MCP Server
 * Auto-generated by Minimal-MCP-Architect
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { initAuth } from "./rc-client.js";

// Import generated tools
import { tool as post_api_v1_users_create } from "./tools/post_api_v1_users_create.js";
import { tool as post_api_v1_users_update } from "./tools/post_api_v1_users_update.js";
import { tool as post_api_v1_channels_invite } from "./tools/post_api_v1_channels_invite.js";
import { tool as post_api_v1_groups_invite } from "./tools/post_api_v1_groups_invite.js";
import { tool as post_api_v1_im_create } from "./tools/post_api_v1_im_create.js";
import { tool as post_api_v1_chat_postMessage } from "./tools/post_api_v1_chat_postMessage.js";
import { tool as get_api_v1_users_info } from "./tools/get_api_v1_users_info.js";
import { tool as provision_vendor_guest } from "./tools/provision_vendor_guest.js";

const server = new McpServer({ 
  name: "rc-vendor-provisioning-mcp", 
  version: "1.0.0" 
});

// Register tools
server.registerTool(
  provision_vendor_guest.name,
  {
    description: provision_vendor_guest.description,
    inputSchema: provision_vendor_guest.inputSchema
  },
  provision_vendor_guest.handler
);
server.registerTool(
  post_api_v1_users_create.name,
  {
    description: post_api_v1_users_create.description,
    inputSchema: post_api_v1_users_create.inputSchema
  },
  post_api_v1_users_create.handler
);
server.registerTool(
  post_api_v1_users_update.name,
  {
    description: post_api_v1_users_update.description,
    inputSchema: post_api_v1_users_update.inputSchema
  },
  post_api_v1_users_update.handler
);
server.registerTool(
  post_api_v1_channels_invite.name,
  {
    description: post_api_v1_channels_invite.description,
    inputSchema: post_api_v1_channels_invite.inputSchema
  },
  post_api_v1_channels_invite.handler
);
server.registerTool(
  post_api_v1_groups_invite.name,
  {
    description: post_api_v1_groups_invite.description,
    inputSchema: post_api_v1_groups_invite.inputSchema
  },
  post_api_v1_groups_invite.handler
);
server.registerTool(
  post_api_v1_im_create.name,
  {
    description: post_api_v1_im_create.description,
    inputSchema: post_api_v1_im_create.inputSchema
  },
  post_api_v1_im_create.handler
);
server.registerTool(
  post_api_v1_chat_postMessage.name,
  {
    description: post_api_v1_chat_postMessage.description,
    inputSchema: post_api_v1_chat_postMessage.inputSchema
  },
  post_api_v1_chat_postMessage.handler
);
server.registerTool(
  get_api_v1_users_info.name,
  {
    description: get_api_v1_users_info.description,
    inputSchema: get_api_v1_users_info.inputSchema
  },
  get_api_v1_users_info.handler
);

async function main() {
  console.error("Initializing Rocket.Chat Auth...");
  await initAuth();
  
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("rc-vendor-provisioning-mcp running on stdio — 7 tools active.");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
