/**
 * Tool: delete_api_apps_appId
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "delete_api_apps_appId",
  description: "/api/apps/{appId}()", // 🚀 The TOON Context Saver
  inputSchema: z.object({
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/apps/{appId}"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables

    return await rcClient.request("DELETE", resolvedPath, { body: args });
  }
};
