/**
 * Tool: get_api_v1_engagement_dashboard_users_active_users
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "get_api_v1_engagement_dashboard_users_active_users",
  description: "engagement-dashboard/users/active-users()", // 🚀 The TOON Context Saver
  inputSchema: z.object({
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/engagement-dashboard/users/active-users"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables

    return await rcClient.request("GET", resolvedPath, { body: args });
  }
};
