/**
 * Tool: get_api_apps_installed
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "get_api_apps_installed",
  description: "/api/apps/installed()", // 🚀 The TOON Context Saver
  inputSchema: z.object({
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/apps/installed"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables

    return await rcClient.request("GET", resolvedPath, { body: args });
  }
};
