/**
 * Tool: post_api_v1_sessions_logout
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_sessions_logout",
  description: "sessions/logout(sessionId:o)", // 🚀 The TOON Context Saver
  inputSchema: z.object({
    sessionId: z.string(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/sessions/logout"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.sessionId !== undefined) {
       const value = encodeURIComponent(String(args.sessionId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "sessionId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("sessionId", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
