/**
 * Tool: post_api_v1_users_update
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_users_update",
  description: "users.upd(uid:o, data:o)", // 🚀 The TOON Context Saver
  inputSchema: z.object({
    userId: z.string(),
    data: z.string(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/users.update"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.userId !== undefined) {
       const value = encodeURIComponent(String(args.userId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "userId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("userId", value);
    }
    if (args.data !== undefined) {
       const value = encodeURIComponent(String(args.data));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "data" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("data", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
