/**
 * Tool: post_api_v1_settings_id
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_settings_id",
  description: "settings/{.id}(value:o, [color:o], [editor:o], [execute:o])", // 🚀 The TOON Context Saver
  inputSchema: z.object({
    value: z.string(),
    color: z.string().optional(),
    editor: z.string().optional(),
    execute: z.boolean().optional(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/settings/{_id}"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.value !== undefined) {
       const value = encodeURIComponent(String(args.value));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "value" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("value", value);
    }
    if (args.color !== undefined) {
       const value = encodeURIComponent(String(args.color));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "color" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("color", value);
    }
    if (args.editor !== undefined) {
       const value = encodeURIComponent(String(args.editor));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "editor" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("editor", value);
    }
    if (args.execute !== undefined) {
       const value = encodeURIComponent(String(args.execute));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "execute" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("execute", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
