/**
 * Tool: post_api_v1_moderation_dismissReports
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_moderation_dismissReports",
  description: "moderation.dismissReports([uid:o], [mid:o])", // 🚀 The TOON Context Saver
  inputSchema: z.object({
    userId: z.string().optional(),
    msgId: z.string().optional(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/moderation.dismissReports"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.userId !== undefined) {
       const value = encodeURIComponent(String(args.userId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "userId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("userId", value);
    }
    if (args.msgId !== undefined) {
       const value = encodeURIComponent(String(args.msgId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "msgId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("msgId", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
