/**
 * Tool: post_api_v1_channels_addAll
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_channels_addAll",
  description: "channels.addAll(rid:o, [activeUsersOnly:o])", //  The TOON Context Saver
  inputSchema: z.object({
    roomId: z.string(),
    activeUsersOnly: z.boolean().optional(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/channels.addAll"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.roomId !== undefined) {
       const value = encodeURIComponent(String(args.roomId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "roomId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("roomId", value);
    }
    if (args.activeUsersOnly !== undefined) {
       const value = encodeURIComponent(String(args.activeUsersOnly));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "activeUsersOnly" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("activeUsersOnly", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
