/**
 * Tool: post_api_v1_channels_create
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_channels_create",
  description: "channels.new(name:o, [members:o], [readOnly:o], [excludeSelf:o], [customFields:o], [extraData:o])", //  The TOON Context Saver
  inputSchema: z.object({
    name: z.string(),
    members: z.array(z.any()).optional(),
    readOnly: z.boolean().optional(),
    excludeSelf: z.boolean().optional(),
    customFields: z.string().optional(),
    extraData: z.string().optional(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/channels.create"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.name !== undefined) {
       const value = encodeURIComponent(String(args.name));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "name" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("name", value);
    }
    if (args.members !== undefined) {
       const value = encodeURIComponent(String(args.members));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "members" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("members", value);
    }
    if (args.readOnly !== undefined) {
       const value = encodeURIComponent(String(args.readOnly));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "readOnly" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("readOnly", value);
    }
    if (args.excludeSelf !== undefined) {
       const value = encodeURIComponent(String(args.excludeSelf));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "excludeSelf" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("excludeSelf", value);
    }
    if (args.customFields !== undefined) {
       const value = encodeURIComponent(String(args.customFields));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "customFields" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("customFields", value);
    }
    if (args.extraData !== undefined) {
       const value = encodeURIComponent(String(args.extraData));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "extraData" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("extraData", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
