/**
 * Tool: get_api_v1_rooms_cleanHistory
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "get_api_v1_rooms_cleanHistory",
  description: "rooms.cleanHistory(rid:o, latest:o, oldest:o, [inclusive:o], [excludePinned:o], [filesOnly:o], [users:o], [limit:o], [ignoreDiscussion:o], [ignoreThreads:o])", // 🚀 The TOON Context Saver
  inputSchema: z.object({
    roomId: z.string(),
    latest: z.string(),
    oldest: z.string(),
    inclusive: z.boolean().optional(),
    excludePinned: z.boolean().optional(),
    filesOnly: z.boolean().optional(),
    users: z.array(z.any()).optional(),
    limit: z.number().optional(),
    ignoreDiscussion: z.boolean().optional(),
    ignoreThreads: z.boolean().optional(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/rooms.cleanHistory"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.roomId !== undefined) {
       const value = encodeURIComponent(String(args.roomId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "roomId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("roomId", value);
    }
    if (args.latest !== undefined) {
       const value = encodeURIComponent(String(args.latest));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "latest" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("latest", value);
    }
    if (args.oldest !== undefined) {
       const value = encodeURIComponent(String(args.oldest));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "oldest" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("oldest", value);
    }
    if (args.inclusive !== undefined) {
       const value = encodeURIComponent(String(args.inclusive));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "inclusive" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("inclusive", value);
    }
    if (args.excludePinned !== undefined) {
       const value = encodeURIComponent(String(args.excludePinned));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "excludePinned" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("excludePinned", value);
    }
    if (args.filesOnly !== undefined) {
       const value = encodeURIComponent(String(args.filesOnly));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "filesOnly" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("filesOnly", value);
    }
    if (args.users !== undefined) {
       const value = encodeURIComponent(String(args.users));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "users" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("users", value);
    }
    if (args.limit !== undefined) {
       const value = encodeURIComponent(String(args.limit));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "limit" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("limit", value);
    }
    if (args.ignoreDiscussion !== undefined) {
       const value = encodeURIComponent(String(args.ignoreDiscussion));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "ignoreDiscussion" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("ignoreDiscussion", value);
    }
    if (args.ignoreThreads !== undefined) {
       const value = encodeURIComponent(String(args.ignoreThreads));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "ignoreThreads" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("ignoreThreads", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
