/**
 * Tool: post_api_v1_integrations_remove
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_integrations_remove",
  description: "integrations.remove(integrationId:o, type:o)", // 🚀 The TOON Context Saver
  inputSchema: z.object({
    integrationId: z.string(),
    type: z.string(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/integrations.remove"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.integrationId !== undefined) {
       const value = encodeURIComponent(String(args.integrationId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "integrationId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("integrationId", value);
    }
    if (args.type !== undefined) {
       const value = encodeURIComponent(String(args.type));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "type" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("type", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
