/**
 * Tool: post_api_v1_chat_delete
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_chat_delete",
  description: "chat.del(rid:o, mid:o, [asUser:o])", // 🚀 The TOON Context Saver
  inputSchema: z.object({
    roomId: z.string(),
    msgId: z.string(),
    asUser: z.boolean().optional(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/chat.delete"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.roomId !== undefined) {
       const value = encodeURIComponent(String(args.roomId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "roomId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("roomId", value);
    }
    if (args.msgId !== undefined) {
       const value = encodeURIComponent(String(args.msgId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "msgId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("msgId", value);
    }
    if (args.asUser !== undefined) {
       const value = encodeURIComponent(String(args.asUser));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "asUser" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("asUser", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
