/**
 * Tool: post_api_v1_groups_kick
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_groups_kick",
  description: "groups.kick(rid:o, uid:o)", // 🚀 The TOON Context Saver
  inputSchema: z.object({
    roomId: z.string(),
    userId: z.string(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/groups.kick"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.roomId !== undefined) {
       const value = encodeURIComponent(String(args.roomId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "roomId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("roomId", value);
    }
    if (args.userId !== undefined) {
       const value = encodeURIComponent(String(args.userId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "userId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("userId", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
