/**
 * Tool: post_api_v1_groups_delete
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_groups_delete",
  description: "groups.del([rid:o], [roomName:o])", // 🚀 The TOON Context Saver
  inputSchema: z.object({
    roomId: z.string().optional(),
    roomName: z.string().optional(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/groups.delete"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.roomId !== undefined) {
       const value = encodeURIComponent(String(args.roomId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "roomId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("roomId", value);
    }
    if (args.roomName !== undefined) {
       const value = encodeURIComponent(String(args.roomName));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "roomName" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("roomName", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
