/**
 * Token-Aware Rocket.Chat API Client
 * Generated by Minimal-MCP-Architect
 */

const MAX_PAYLOAD_BYTES = 8192; // 8KB truncation limit to protect LLM context

const config = {
  baseUrl: process.env.ROCKETCHAT_URL || "http://localhost:3000",
  authToken: process.env.ROCKETCHAT_AUTH_TOKEN || "",
  userId: process.env.ROCKETCHAT_USER_ID || "",
};

export type ToolResult = { content: { type: "text"; text: string }[]; isError?: boolean };

let initialized = false;

export async function initAuth(): Promise<void> {
  if (initialized) return;
  initialized = true;

  const user = process.env.ROCKETCHAT_USER;
  const password = process.env.ROCKETCHAT_PASSWORD;

  if (user && password) {
    const res = await fetch(`${config.baseUrl}/api/v1/login`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ user, password }),
    });
    let data;
    const text = await res.text();
    try {
      data = JSON.parse(text);
    } catch (e) {
      console.error(`[MCP] Login failed. The server at ${config.baseUrl} did not return JSON.`);
      console.error(`[MCP] Status code: ${res.status}`);
      console.error(`[MCP] Response started with: ${text.substring(0, 100).replace(/\n/g, ' ')}`);
      process.exit(1);
    }

    if (!res.ok || !data.data?.authToken) {
      console.error("[MCP] Login failed. Check ROCKETCHAT_USER / ROCKETCHAT_PASSWORD or server URL.");
      process.exit(1);
    }
    config.authToken = data.data.authToken;
    config.userId = data.data.userId;
    console.error(`[MCP] Authenticated as ${user}`);
    return;
  }

  if (!config.authToken || !config.userId) {
    console.error("[MCP] Fatal: No Auth credentials found in environment.");
    process.exit(1);
  }
}

class RocketChatClient {
  private pruneResponse(data: any): string {
    const rawString = JSON.stringify(data);
    if (rawString.length <= MAX_PAYLOAD_BYTES) {
      return JSON.stringify(data, null, 2);
    }

    console.warn(`[MCP] Payload exceeded ${MAX_PAYLOAD_BYTES} bytes. Truncating to save LLM context.`);
    
    // Intelligent truncation for arrays (messages, rooms, users)
    const arrayKey = Object.keys(data).find(k => Array.isArray(data[k]));
    if (arrayKey) {
       data[arrayKey] = data[arrayKey].slice(0, 5); // Keep top 5 only
       data._mcp_warning = `Payload truncated. Use pagination/offset to see more.`;
       return JSON.stringify(data, null, 2);
    }

    return rawString.substring(0, MAX_PAYLOAD_BYTES) + "\n... [TRUNCATED DUE TO SIZE]";
  }

  async request(method: string, path: string, options: any = {}): Promise<ToolResult> {
    const url = `${config.baseUrl}${path}`;
    const headers: Record<string, string> = { 
      "Content-Type": "application/json", 
      "X-Auth-Token": config.authToken,
      "X-User-Id": config.userId,
      ...options.headers 
    };

    const fetchOpts: RequestInit = { method, headers };
    if (options.body) fetchOpts.body = JSON.stringify(options.body);

    let retries = 0;
    const maxRetries = 3;
    let res;

    // 429 Exponential Backoff Loop
    while (retries <= maxRetries) {
      res = await fetch(url, fetchOpts);
      if (res.status !== 429) break;
      
      const retryAfter = res.headers.get("Retry-After");
      const waitTime = retryAfter ? parseInt(retryAfter) * 1000 : Math.pow(2, retries) * 1000;
      console.warn(`[MCP] Rate limited (429). Agent pausing for ${waitTime}ms...`);
      await new Promise(r => setTimeout(r, waitTime));
      retries++;
    }

    let data;
    try { data = await res!.json(); } catch { data = { error: "Invalid JSON from server" }; }

    if (!res!.ok) {
      return { content: [{ type: "text", text: `[Error ${res!.status}] ${JSON.stringify(data)}` }], isError: true };
    }

    return { content: [{ type: "text", text: this.pruneResponse(data) }] };
  }
}

export const rcClient = new RocketChatClient();
