#!/usr/bin/env node
/**
 * rc-channel-archival-mcp — MCP Server
 * Auto-generated by Minimal-MCP-Architect
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { initAuth } from "./rc-client.js";

// Import generated tools
import { tool as post_api_v1_rooms_export } from "./tools/post_api_v1_rooms_export.js";
import { tool as get_api_v1_channels_members } from "./tools/get_api_v1_channels_members.js";
import { tool as post_api_v1_channels_kick } from "./tools/post_api_v1_channels_kick.js";
import { tool as post_api_v1_channels_archive } from "./tools/post_api_v1_channels_archive.js";
import { tool as get_api_v1_groups_members } from "./tools/get_api_v1_groups_members.js";
import { tool as post_api_v1_groups_kick } from "./tools/post_api_v1_groups_kick.js";
import { tool as post_api_v1_groups_archive } from "./tools/post_api_v1_groups_archive.js";
import { tool as post_api_v1_chat_postMessage } from "./tools/post_api_v1_chat_postMessage.js";
import { tool as archive_and_audit_channel } from "./tools/archive_and_audit_channel.js";

const server = new McpServer({ 
  name: "rc-channel-archival-mcp", 
  version: "1.0.0" 
});

// Register tools
server.registerTool(
  archive_and_audit_channel.name,
  {
    description: archive_and_audit_channel.description,
    inputSchema: archive_and_audit_channel.inputSchema
  },
  archive_and_audit_channel.handler
);
server.registerTool(
  post_api_v1_rooms_export.name,
  {
    description: post_api_v1_rooms_export.description,
    inputSchema: post_api_v1_rooms_export.inputSchema
  },
  post_api_v1_rooms_export.handler
);
server.registerTool(
  get_api_v1_channels_members.name,
  {
    description: get_api_v1_channels_members.description,
    inputSchema: get_api_v1_channels_members.inputSchema
  },
  get_api_v1_channels_members.handler
);
server.registerTool(
  post_api_v1_channels_kick.name,
  {
    description: post_api_v1_channels_kick.description,
    inputSchema: post_api_v1_channels_kick.inputSchema
  },
  post_api_v1_channels_kick.handler
);
server.registerTool(
  post_api_v1_channels_archive.name,
  {
    description: post_api_v1_channels_archive.description,
    inputSchema: post_api_v1_channels_archive.inputSchema
  },
  post_api_v1_channels_archive.handler
);
server.registerTool(
  get_api_v1_groups_members.name,
  {
    description: get_api_v1_groups_members.description,
    inputSchema: get_api_v1_groups_members.inputSchema
  },
  get_api_v1_groups_members.handler
);
server.registerTool(
  post_api_v1_groups_kick.name,
  {
    description: post_api_v1_groups_kick.description,
    inputSchema: post_api_v1_groups_kick.inputSchema
  },
  post_api_v1_groups_kick.handler
);
server.registerTool(
  post_api_v1_groups_archive.name,
  {
    description: post_api_v1_groups_archive.description,
    inputSchema: post_api_v1_groups_archive.inputSchema
  },
  post_api_v1_groups_archive.handler
);
server.registerTool(
  post_api_v1_chat_postMessage.name,
  {
    description: post_api_v1_chat_postMessage.description,
    inputSchema: post_api_v1_chat_postMessage.inputSchema
  },
  post_api_v1_chat_postMessage.handler
);

async function main() {
  console.error("Initializing Rocket.Chat Auth...");
  await initAuth();
  
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("rc-channel-archival-mcp running on stdio — 8 tools active.");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
