/**
 * Tool: post_api_v1_integrations_create
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_integrations_create",
  description: "integrations.new(type:o, u:o, channel:o, scriptEnabled:o, [script:o], name:o, enabled:o, [alias:o], [avatar:o], [emoji:o], event:o, urls:o, [triggerWords:o], [token:o])", //  The TOON Context Saver
  inputSchema: z.object({
    type: z.string(),
    username: z.string(),
    channel: z.string(),
    scriptEnabled: z.boolean(),
    script: z.string().optional(),
    name: z.string(),
    enabled: z.boolean(),
    alias: z.string().optional(),
    avatar: z.string().optional(),
    emoji: z.string().optional(),
    event: z.string(),
    urls: z.array(z.any()),
    triggerWords: z.string().optional(),
    token: z.string().optional(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/integrations.create"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.type !== undefined) {
       const value = encodeURIComponent(String(args.type));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "type" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("type", value);
    }
    if (args.username !== undefined) {
       const value = encodeURIComponent(String(args.username));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "username" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("username", value);
    }
    if (args.channel !== undefined) {
       const value = encodeURIComponent(String(args.channel));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "channel" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("channel", value);
    }
    if (args.scriptEnabled !== undefined) {
       const value = encodeURIComponent(String(args.scriptEnabled));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "scriptEnabled" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("scriptEnabled", value);
    }
    if (args.script !== undefined) {
       const value = encodeURIComponent(String(args.script));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "script" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("script", value);
    }
    if (args.name !== undefined) {
       const value = encodeURIComponent(String(args.name));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "name" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("name", value);
    }
    if (args.enabled !== undefined) {
       const value = encodeURIComponent(String(args.enabled));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "enabled" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("enabled", value);
    }
    if (args.alias !== undefined) {
       const value = encodeURIComponent(String(args.alias));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "alias" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("alias", value);
    }
    if (args.avatar !== undefined) {
       const value = encodeURIComponent(String(args.avatar));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "avatar" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("avatar", value);
    }
    if (args.emoji !== undefined) {
       const value = encodeURIComponent(String(args.emoji));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "emoji" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("emoji", value);
    }
    if (args.event !== undefined) {
       const value = encodeURIComponent(String(args.event));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "event" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("event", value);
    }
    if (args.urls !== undefined) {
       const value = encodeURIComponent(String(args.urls));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "urls" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("urls", value);
    }
    if (args.triggerWords !== undefined) {
       const value = encodeURIComponent(String(args.triggerWords));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "triggerWords" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("triggerWords", value);
    }
    if (args.token !== undefined) {
       const value = encodeURIComponent(String(args.token));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "token" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("token", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
