#!/usr/bin/env node
/**
 * rc-user-onboarding-mcp — MCP Server
 * Auto-generated by Minimal-MCP-Architect
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { initAuth } from "./rc-client.js";

// Import generated tools
import { tool as post_api_v1_users_create } from "./tools/post_api_v1_users_create.js";
import { tool as post_api_v1_roles_addUserToRole } from "./tools/post_api_v1_roles_addUserToRole.js";
import { tool as post_api_v1_channels_invite } from "./tools/post_api_v1_channels_invite.js";
import { tool as post_api_v1_im_create } from "./tools/post_api_v1_im_create.js";
import { tool as post_api_v1_chat_postMessage } from "./tools/post_api_v1_chat_postMessage.js";

const server = new McpServer({ 
  name: "rc-user-onboarding-mcp", 
  version: "1.0.0" 
});

// Register tools
server.registerTool(
  post_api_v1_users_create.name,
  {
    description: post_api_v1_users_create.description,
    inputSchema: post_api_v1_users_create.inputSchema
  },
  post_api_v1_users_create.handler
);
server.registerTool(
  post_api_v1_roles_addUserToRole.name,
  {
    description: post_api_v1_roles_addUserToRole.description,
    inputSchema: post_api_v1_roles_addUserToRole.inputSchema
  },
  post_api_v1_roles_addUserToRole.handler
);
server.registerTool(
  post_api_v1_channels_invite.name,
  {
    description: post_api_v1_channels_invite.description,
    inputSchema: post_api_v1_channels_invite.inputSchema
  },
  post_api_v1_channels_invite.handler
);
server.registerTool(
  post_api_v1_im_create.name,
  {
    description: post_api_v1_im_create.description,
    inputSchema: post_api_v1_im_create.inputSchema
  },
  post_api_v1_im_create.handler
);
server.registerTool(
  post_api_v1_chat_postMessage.name,
  {
    description: post_api_v1_chat_postMessage.description,
    inputSchema: post_api_v1_chat_postMessage.inputSchema
  },
  post_api_v1_chat_postMessage.handler
);

async function main() {
  console.error("Initializing Rocket.Chat Auth...");
  await initAuth();
  
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("rc-user-onboarding-mcp running on stdio — 5 tools active.");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
