/**
 * Tool: post_api_v1_users_create
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_users_create",
  description: "users.new(name:o, email:o, password:o, u:o, [active:o], [nickname:o], [bio:o], [joinDefaultChannels:o], [statusText:o], [roles:o], [requirePasswordChange:o], [setRandomPassword:o], [sendWelcomeEmail:o], [verified:o], [customFields:o])", //  The TOON Context Saver
  inputSchema: z.object({
    name: z.string(),
    email: z.string(),
    password: z.string(),
    username: z.string(),
    active: z.boolean().optional(),
    nickname: z.string().optional(),
    bio: z.string().optional(),
    joinDefaultChannels: z.boolean().optional(),
    statusText: z.string().optional(),
    roles: z.array(z.any()).optional(),
    requirePasswordChange: z.boolean().optional(),
    setRandomPassword: z.boolean().optional(),
    sendWelcomeEmail: z.boolean().optional(),
    verified: z.boolean().optional(),
    customFields: z.string().optional(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/users.create"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.name !== undefined) {
       const value = encodeURIComponent(String(args.name));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "name" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("name", value);
    }
    if (args.email !== undefined) {
       const value = encodeURIComponent(String(args.email));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "email" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("email", value);
    }
    if (args.password !== undefined) {
       const value = encodeURIComponent(String(args.password));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "password" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("password", value);
    }
    if (args.username !== undefined) {
       const value = encodeURIComponent(String(args.username));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "username" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("username", value);
    }
    if (args.active !== undefined) {
       const value = encodeURIComponent(String(args.active));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "active" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("active", value);
    }
    if (args.nickname !== undefined) {
       const value = encodeURIComponent(String(args.nickname));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "nickname" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("nickname", value);
    }
    if (args.bio !== undefined) {
       const value = encodeURIComponent(String(args.bio));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "bio" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("bio", value);
    }
    if (args.joinDefaultChannels !== undefined) {
       const value = encodeURIComponent(String(args.joinDefaultChannels));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "joinDefaultChannels" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("joinDefaultChannels", value);
    }
    if (args.statusText !== undefined) {
       const value = encodeURIComponent(String(args.statusText));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "statusText" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("statusText", value);
    }
    if (args.roles !== undefined) {
       const value = encodeURIComponent(String(args.roles));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "roles" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("roles", value);
    }
    if (args.requirePasswordChange !== undefined) {
       const value = encodeURIComponent(String(args.requirePasswordChange));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "requirePasswordChange" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("requirePasswordChange", value);
    }
    if (args.setRandomPassword !== undefined) {
       const value = encodeURIComponent(String(args.setRandomPassword));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "setRandomPassword" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("setRandomPassword", value);
    }
    if (args.sendWelcomeEmail !== undefined) {
       const value = encodeURIComponent(String(args.sendWelcomeEmail));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "sendWelcomeEmail" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("sendWelcomeEmail", value);
    }
    if (args.verified !== undefined) {
       const value = encodeURIComponent(String(args.verified));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "verified" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("verified", value);
    }
    if (args.customFields !== undefined) {
       const value = encodeURIComponent(String(args.customFields));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "customFields" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("customFields", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
