#!/usr/bin/env node
/**
 * rc-cleanup-bot — MCP Server
 * Auto-generated by Minimal-MCP-Architect
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { initAuth } from "./rc-client.js";

// Import generated tools
import { tool as post_api_v1_chat_delete } from "./tools/post_api_v1_chat_delete.js";
import { tool as post_api_v1_channels_delete } from "./tools/post_api_v1_channels_delete.js";
import { tool as post_api_v1_groups_delete } from "./tools/post_api_v1_groups_delete.js";
import { tool as post_api_v1_channels_kick } from "./tools/post_api_v1_channels_kick.js";
import { tool as post_api_v1_groups_kick } from "./tools/post_api_v1_groups_kick.js";
import { tool as post_api_v1_integrations_remove } from "./tools/post_api_v1_integrations_remove.js";
import { tool as get_api_v1_rooms_cleanHistory } from "./tools/get_api_v1_rooms_cleanHistory.js";
import { tool as get_api_v1_channels_list } from "./tools/get_api_v1_channels_list.js";
import { tool as get_api_v1_groups_list } from "./tools/get_api_v1_groups_list.js";
import { tool as get_api_v1_integrations_list } from "./tools/get_api_v1_integrations_list.js";

const server = new McpServer({ 
  name: "rc-cleanup-bot", 
  version: "1.0.0" 
});

// Register tools
server.registerTool(
  post_api_v1_chat_delete.name,
  {
    description: post_api_v1_chat_delete.description,
    inputSchema: post_api_v1_chat_delete.inputSchema
  },
  post_api_v1_chat_delete.handler
);
server.registerTool(
  post_api_v1_channels_delete.name,
  {
    description: post_api_v1_channels_delete.description,
    inputSchema: post_api_v1_channels_delete.inputSchema
  },
  post_api_v1_channels_delete.handler
);
server.registerTool(
  post_api_v1_groups_delete.name,
  {
    description: post_api_v1_groups_delete.description,
    inputSchema: post_api_v1_groups_delete.inputSchema
  },
  post_api_v1_groups_delete.handler
);
server.registerTool(
  post_api_v1_channels_kick.name,
  {
    description: post_api_v1_channels_kick.description,
    inputSchema: post_api_v1_channels_kick.inputSchema
  },
  post_api_v1_channels_kick.handler
);
server.registerTool(
  post_api_v1_groups_kick.name,
  {
    description: post_api_v1_groups_kick.description,
    inputSchema: post_api_v1_groups_kick.inputSchema
  },
  post_api_v1_groups_kick.handler
);
server.registerTool(
  post_api_v1_integrations_remove.name,
  {
    description: post_api_v1_integrations_remove.description,
    inputSchema: post_api_v1_integrations_remove.inputSchema
  },
  post_api_v1_integrations_remove.handler
);
server.registerTool(
  get_api_v1_rooms_cleanHistory.name,
  {
    description: get_api_v1_rooms_cleanHistory.description,
    inputSchema: get_api_v1_rooms_cleanHistory.inputSchema
  },
  get_api_v1_rooms_cleanHistory.handler
);
server.registerTool(
  get_api_v1_channels_list.name,
  {
    description: get_api_v1_channels_list.description,
    inputSchema: get_api_v1_channels_list.inputSchema
  },
  get_api_v1_channels_list.handler
);
server.registerTool(
  get_api_v1_groups_list.name,
  {
    description: get_api_v1_groups_list.description,
    inputSchema: get_api_v1_groups_list.inputSchema
  },
  get_api_v1_groups_list.handler
);
server.registerTool(
  get_api_v1_integrations_list.name,
  {
    description: get_api_v1_integrations_list.description,
    inputSchema: get_api_v1_integrations_list.inputSchema
  },
  get_api_v1_integrations_list.handler
);

async function main() {
  console.error("Initializing Rocket.Chat Auth...");
  await initAuth();
  
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("rc-cleanup-bot running on stdio — 10 tools active.");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
