/**
 * Tool: post_api_v1_users_setActiveStatus
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_users_setActiveStatus",
  description: "users.setActiveStatus(activeStatus:o, uid:o, [confirmRelinquish:o])", //  The TOON Context Saver
  inputSchema: z.object({
    activeStatus: z.boolean(),
    userId: z.string(),
    confirmRelinquish: z.boolean().optional(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/users.setActiveStatus"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.activeStatus !== undefined) {
       const value = encodeURIComponent(String(args.activeStatus));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "activeStatus" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("activeStatus", value);
    }
    if (args.userId !== undefined) {
       const value = encodeURIComponent(String(args.userId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "userId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("userId", value);
    }
    if (args.confirmRelinquish !== undefined) {
       const value = encodeURIComponent(String(args.confirmRelinquish));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "confirmRelinquish" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("confirmRelinquish", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
