/**
 * Tool: post_api_v1_users_logoutOtherClients
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_users_logoutOtherClients",
  description: "users.logoutOtherClients()", //  The TOON Context Saver
  inputSchema: z.object({
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/users.logoutOtherClients"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
