#!/usr/bin/env node
/**
 * rc-company-broadcast-mcp — MCP Server
 * Auto-generated by Minimal-MCP-Architect
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { initAuth } from "./rc-client.js";

// Import generated tools
import { tool as get_api_v1_users_list } from "./tools/get_api_v1_users_list.js";
import { tool as post_api_v1_channels_create } from "./tools/post_api_v1_channels_create.js";
import { tool as post_api_v1_channels_addAll } from "./tools/post_api_v1_channels_addAll.js";
import { tool as post_api_v1_chat_postMessage } from "./tools/post_api_v1_chat_postMessage.js";
import { tool as get_api_v1_chat_getMessage } from "./tools/get_api_v1_chat_getMessage.js";
import { tool as broadcast_announcement } from "./tools/broadcast_announcement.js";
import { tool as get_message_metrics } from "./tools/get_message_metrics.js";

const server = new McpServer({ 
  name: "rc-company-broadcast-mcp", 
  version: "1.0.0" 
});

// Register tools
server.registerTool(
  broadcast_announcement.name,
  {
    description: broadcast_announcement.description,
    inputSchema: broadcast_announcement.inputSchema
  },
  broadcast_announcement.handler
);
server.registerTool(
  get_message_metrics.name,
  {
    description: get_message_metrics.description,
    inputSchema: get_message_metrics.inputSchema
  },
  get_message_metrics.handler
);
server.registerTool(
  get_api_v1_users_list.name,
  {
    description: get_api_v1_users_list.description,
    inputSchema: get_api_v1_users_list.inputSchema
  },
  get_api_v1_users_list.handler
);
server.registerTool(
  post_api_v1_channels_create.name,
  {
    description: post_api_v1_channels_create.description,
    inputSchema: post_api_v1_channels_create.inputSchema
  },
  post_api_v1_channels_create.handler
);
server.registerTool(
  post_api_v1_channels_addAll.name,
  {
    description: post_api_v1_channels_addAll.description,
    inputSchema: post_api_v1_channels_addAll.inputSchema
  },
  post_api_v1_channels_addAll.handler
);
server.registerTool(
  post_api_v1_chat_postMessage.name,
  {
    description: post_api_v1_chat_postMessage.description,
    inputSchema: post_api_v1_chat_postMessage.inputSchema
  },
  post_api_v1_chat_postMessage.handler
);
server.registerTool(
  get_api_v1_chat_getMessage.name,
  {
    description: get_api_v1_chat_getMessage.description,
    inputSchema: get_api_v1_chat_getMessage.inputSchema
  },
  get_api_v1_chat_getMessage.handler
);

async function main() {
  console.error("Initializing Rocket.Chat Auth...");
  await initAuth();
  
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("rc-company-broadcast-mcp running on stdio — 5 tools active.");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
