/**
 * Tool: post_api_v1_rooms_export
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_rooms_export",
  description: "rooms.export(rid:o, type:o, [dateFrom:o], [dateTo:o], [format:o], [toUsers:o], [toEmails:o], [messages:o], [subject:o])", //  The TOON Context Saver
  inputSchema: z.object({
    rid: z.string(),
    type: z.string(),
    dateFrom: z.string().optional(),
    dateTo: z.string().optional(),
    format: z.string().optional(),
    toUsers: z.array(z.any()).optional(),
    toEmails: z.array(z.any()).optional(),
    messages: z.array(z.any()).optional(),
    subject: z.string().optional(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/rooms.export"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.rid !== undefined) {
       const value = encodeURIComponent(String(args.rid));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "rid" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("rid", value);
    }
    if (args.type !== undefined) {
       const value = encodeURIComponent(String(args.type));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "type" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("type", value);
    }
    if (args.dateFrom !== undefined) {
       const value = encodeURIComponent(String(args.dateFrom));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "dateFrom" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("dateFrom", value);
    }
    if (args.dateTo !== undefined) {
       const value = encodeURIComponent(String(args.dateTo));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "dateTo" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("dateTo", value);
    }
    if (args.format !== undefined) {
       const value = encodeURIComponent(String(args.format));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "format" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("format", value);
    }
    if (args.toUsers !== undefined) {
       const value = encodeURIComponent(String(args.toUsers));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "toUsers" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("toUsers", value);
    }
    if (args.toEmails !== undefined) {
       const value = encodeURIComponent(String(args.toEmails));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "toEmails" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("toEmails", value);
    }
    if (args.messages !== undefined) {
       const value = encodeURIComponent(String(args.messages));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "messages" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("messages", value);
    }
    if (args.subject !== undefined) {
       const value = encodeURIComponent(String(args.subject));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "subject" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("subject", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
