/**
 * Tool: post_api_v1_groups_archive
 * Generated by Minimal-MCP-Architect
 */
import { rcClient } from "../rc-client.js";
import { z } from "zod";

export const tool = {
  name: "post_api_v1_groups_archive",
  description: "groups.archive(rid:o)", //  The TOON Context Saver
  inputSchema: z.object({
    roomId: z.string(),
  }),
  handler: async (args: any) => {
    let resolvedPath = "/api/v1/groups.archive"; // e.g., "/api/v1/settings/{_id}"
    
    // Dynamically replace path variables
    if (args.roomId !== undefined) {
       const value = encodeURIComponent(String(args.roomId));
       // Replace the bracketed version `{paramName}`
       resolvedPath = resolvedPath.replace("{" + "roomId" + "}", value);
       // Fallback: replace the raw string just in case
       resolvedPath = resolvedPath.replace("roomId", value);
    }

    return await rcClient.request("POST", resolvedPath, { body: args });
  }
};
